setTimeout(()=>{
    document.getElementById("a1").innerHTML=10
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=9
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=8
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=7
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=6
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=5
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=4
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=3
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=2
    setTimeout(()=>{
    document.getElementById("a1").innerHTML=1
    setTimeout(()=>{
    document.getElementById("a1").innerHTML="sparkles"
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)   
},1000)                                                                                       